//FETCH DATA ACTIONS
export const FETCH_ALBUMS = "FETCH_ALBUMS"
export const FETCH_ARTISTS = "FETCH_ARTISTS"
export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS"
export const FETCH_TRACKS = "FETCH_TRACKS"

// PLAYER ACTIONS


