// FETCH DATA ACTIONS
export const FETCH_ALBUMS = "FETCH_ALBUMS"
export const FETCH_ARTISTS = "FETCH_ARTISTS"
export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS"
export const FETCH_TRACKS = "FETCH_TRACKS"

// PLAYER ACTIONS
export const GET_TRACK_INFO= "GET_TRACK_INFO"
export const PLAYBACK_ON = "PLAYBACK_ON"
export const PAUSE_TRACK = "PAUSE_TRACK"
export const NEXT_TRACK = "NEXT_TRACK"
export const PREVIOUS_TRACK = "PREVIOUS_TRACK"
export const SHUFFLE_TRACKS = "SHUFFLE_TRACKS"
export const REPEAT_CYCLE = "REPEAT_CYCLE"

// AUTH ACTIONS
export const GET_DEVICEID = "GET_DEVICEID"
export const GET_PARAMS = "GET_PARAMS"
export const GET_TOKEN = "GET_TOKEN"
export const GET_EXPIRE_TIME = "GET_EXPIRE_TIME"
export const LOGIN = "LOGIN"
